version: '3'

services:
    nginx:
        container_name: "agenda_nginx"
        build:
            context: ./services/nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./agenda:/var/www/html
            - ./services/nginx/logs:/var/log/nginx
            - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
           - php-fpm
           - mysql
        
    php-fpm:
        container_name: "agenda_php-fpm"
        build:
            context: ./services/php-fpm
            dockerfile: Dockerfile
        expose: 
            - "9000"
        volumes:
            - ./agenda:/var/www/html

    mysql:
        container_name: "agenda_mysql"
        build:
           context: ./services/mysql
           dockerfile: Dockerfile
        ports:
            - "3306:3306"
        volumes:
            - ./services/mysql/data:/var/lib/mysql:rw
            - ./services/mysql/initdb:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: 1q2w3e